/* for get data */

export let GET_DATA_REQUEST = "GET_DATA_REQUEST";
export let GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export let GET_DATA_PENDING = "GET_DATA_PENDING";

/* for post data */

export let POST_DATA_REQUEST = "POST_DATA_REQUEST";
export let POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export let POST_DATA_PENDING = "POST_DATA_PENDING";